### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
This file should live in a .github repo and not in any individual repo.

**Review by romulocintra — APPROVED** [review]

**Comment by ljharb** [comment]
@egasimus the place to discuss this would be on the code of conduct repo itself, not here. I'm going to hide these as off topic.

**Comment by ctcpip** [comment]
> This file should live in a .github repo and not in any individual repo.

It's on my list :)

**Comment by ljharb** [comment]
LGTM

**Pull request merged**
